schema_version: 1
name: e2e-rust-cli
version: "1.0.3"
description: "E2E test plugin: Rust CLI with onchainos price query"
author:
  name: "yz06276"
  github: "yz06276"
license: MIT
category: utility
tags: [e2e-test, rust, cli]
components:
  skill:
    dir: skills/e2e-rust-cli
build:
  lang: rust
  source_repo: yz06276/e2e-rust-cli
  source_commit: "feeb3eec2d84edb7b3bd8444ca00ef5015d7d6ee"
  source_dir: "."
  binary_name: e2e-rust-cli
api_calls: []
